<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.5</version>
    </parent>

    <groupId>org.foomaa.jvchat</groupId>
    <artifactId>JvChat</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>JvChat</name>

    <modules>
        <module>sources/lib/Settings</module>
        <module>sources/lib/UIComponents</module>
        <module>sources/lib/Tools</module>
        <module>sources/lib/Cryptography</module>
        <module>sources/lib/Logger</module>
        <module>sources/lib/GlobalDefines</module>
        <module>sources/lib/Messages</module>
        <module>sources/lib/Signals</module>
        <module>sources/lib/Models</module>
        <module>sources/lib/StructObjects</module>
        <module>sources/src/StartPoint</module>
        <module>sources/src/UILinks</module>
        <module>sources/src/DbWorker</module>
        <module>sources/src/Controls</module>
        <module>sources/src/Network</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <version.exec-maven-plugin>3.1.0</version.exec-maven-plugin>
        <maven.test.skip>true</maven.test.skip>
        <buildDir>jvchat-maven</buildDir>
        <skip.spring.boot>false</skip.spring.boot>
    </properties>

    <profiles>
        <profile>
            <id>tests</id>
            <properties>
                <spring.profiles.active>tests</spring.profiles.active>
                <maven.test.skip>false</maven.test.skip>
                <skip.spring.boot>true</skip.spring.boot>
            </properties>
        </profile>

        <profile>
            <id>users</id>
            <properties>
                <spring.profiles.active>users</spring.profiles.active>
                <maven.test.skip>true</maven.test.skip>
                <skip.spring.boot>false</skip.spring.boot>
            </properties>
        </profile>

        <profile>
            <id>servers</id>
            <properties>
                <spring.profiles.active>servers</spring.profiles.active>
                <maven.test.skip>true</maven.test.skip>
                <skip.spring.boot>false</skip.spring.boot>
            </properties>
        </profile>
    </profiles>

    <build>
        <directory>${buildDir}</directory>

        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>none</mainClass>
                    <systemPropertyVariables>
                        <spring.profiles.active>${spring.profiles.active}</spring.profiles.active>
                    </systemPropertyVariables>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>

                <configuration>
                    <source>17</source>
                    <target>17</target>

                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.30</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.32.0</version>

                <configuration>
                    <java>
                        <palantirJavaFormat/>
                        <importOrder>
                            <order>java,javax,org,com,lombok,org.foomaa.jvchat,</order>
                        </importOrder>
                        <removeUnusedImports/>
                        <trimTrailingWhitespace/>
                        <endWithNewline/>
                        <excludes>**/*_pb.java</excludes>
                    </java>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
