import java.io.File

rootProject.name = "JvChat"

include("Settings")
project(":Settings").projectDir = File("sources/lib/Settings")
include("Tools")
project(":Tools").projectDir = File("sources/lib/Tools")
include("Cryptography")
project(":Cryptography").projectDir = File("sources/lib/Cryptography")
include("Logger")
project(":Logger").projectDir = File("sources/lib/Logger")
include("GlobalDefines")
project(":GlobalDefines").projectDir = File("sources/lib/GlobalDefines")
include("Messages")
project(":Messages").projectDir = File("sources/lib/Messages")
include("UIComponents")
project(":UIComponents").projectDir = File("sources/lib/UIComponents")
include("AuthUIComponents")
project(":AuthUIComponents").projectDir = File("sources/lib/UIComponents/AuthUIComponents")
include("Events")
project(":Events").projectDir = File("sources/lib/Events")
include("JvMainChatUIComponents")
project(":JvMainChatUIComponents").projectDir = File("sources/lib/UIComponents/JvMainChatUIComponents")
include("Models")
project(":Models").projectDir = File("sources/lib/Models")
include("StructObjects")
project(":StructObjects").projectDir = File("sources/lib/StructObjects")
include("StartPoint")
project(":StartPoint").projectDir = File("sources/src/StartPoint")
include("UILinks")
project(":UILinks").projectDir = File("sources/src/UILinks")
include("DbWorker")
project(":DbWorker").projectDir = File("sources/src/DbWorker")
include("Controls")
project(":Controls").projectDir = File("sources/src/Controls")
include("Network")
project(":Network").projectDir = File("sources/src/Network")
// findProject("sources:lib:UIComponents:AuthUIComponents")?.name = "AuthUIComponents"