import java.io.File

rootProject.name = "JvChat"

include("JvStartPoint")
project(":JvStartPoint").projectDir = File("sources/src/JvStartPoint")
include("JvUILinks")
project(":JvUILinks").projectDir = File("sources/src/JvUILinks")
include("JvDbWorker")
project(":JvDbWorker").projectDir = File("sources/src/JvDbWorker")
include("JvControls")
project(":JvControls").projectDir = File("sources/src/JvControls")
include("JvModels")
project(":JvModels").projectDir = File("sources/src/JvModels")
include("JvStructObjects")
project(":JvStructObjects").projectDir = File("sources/src/JvStructObjects")
include("JvNetwork")
project(":JvNetwork").projectDir = File("sources/src/JvNetwork")
include("JvSettings")
project(":JvSettings").projectDir = File("sources/lib/JvSettings")
include("JvTools")
project(":JvTools").projectDir = File("sources/lib/JvTools")
include("JvCryptography")
project(":JvCryptography").projectDir = File("sources/lib/JvCryptography")
include("JvLogger")
project(":JvLogger").projectDir = File("sources/lib/JvLogger")
include("JvGlobalDefines")
project(":JvGlobalDefines").projectDir = File("sources/lib/JvGlobalDefines")
include("JvMessages")
project(":JvMessages").projectDir = File("sources/lib/JvMessages")
include("JvUIComponents")
project(":JvUIComponents").projectDir = File("sources/lib/JvUIComponents")
include("JvAuthUIComponents")
project(":JvAuthUIComponents").projectDir = File("sources/lib/JvUIComponents/JvAuthUIComponents")
include("JvMainChatUIComponents")
project(":JvMainChatUIComponents").projectDir = File("sources/lib/JvUIComponents/JvMainChatUIComponents")

// findProject("sources:lib:JvUIComponents:JvAuthUIComponents")?.name = "JvAuthUIComponents"