import java.io.File

rootProject.name = "JvChat"

include("JvSettings")
project(":JvSettings").projectDir = File("sources/lib/JvSettings")
include("JvTools")
project(":JvTools").projectDir = File("sources/lib/JvTools")
include("JvCryptography")
project(":JvCryptography").projectDir = File("sources/lib/JvCryptography")
include("JvLogger")
project(":JvLogger").projectDir = File("sources/lib/JvLogger")
include("JvGlobalDefines")
project(":JvGlobalDefines").projectDir = File("sources/lib/JvGlobalDefines")
include("JvMessages")
project(":JvMessages").projectDir = File("sources/lib/JvMessages")
include("JvUIComponents")
project(":JvUIComponents").projectDir = File("sources/lib/JvUIComponents")
include("JvAuthUIComponents")
project(":JvAuthUIComponents").projectDir = File("sources/lib/JvUIComponents/JvAuthUIComponents")
include("JvEvents")
project(":JvEvents").projectDir = File("sources/lib/JvEvents")
include("JvMainChatUIComponents")
project(":JvMainChatUIComponents").projectDir = File("sources/lib/JvUIComponents/JvMainChatUIComponents")
include("JvModels")
project(":JvModels").projectDir = File("sources/lib/JvModels")
include("JvStructObjects")
project(":JvStructObjects").projectDir = File("sources/lib/JvStructObjects")
include("StartPoint")
project(":StartPoint").projectDir = File("sources/src/StartPoint")
include("UILinks")
project(":UILinks").projectDir = File("sources/src/UILinks")
include("DbWorker")
project(":DbWorker").projectDir = File("sources/src/DbWorker")
include("JvControls")
project(":JvControls").projectDir = File("sources/src/JvControls")
include("Network")
project(":Network").projectDir = File("sources/src/Network")
// findProject("sources:lib:JvUIComponents:JvAuthUIComponents")?.name = "JvAuthUIComponents"