<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.foomaa.jvchat</groupId>
        <artifactId>JvChat</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <groupId>org.foomaa.jvchat.startpoint</groupId>
    <artifactId>StartPoint</artifactId>
    <packaging>jar</packaging>

    <name>StartPoint</name>

    <properties>
        <mainClass>org.foomaa.jvchat.startpoint.MainStartPoint</mainClass>
        <exec.skip>false</exec.skip>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Profile>${spring.profiles.active}</Profile>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${mainClass}</mainClass>
                    <systemPropertyVariables>
                        <spring.profiles.active>${spring.profiles.active}</spring.profiles.active>
                        <skip.spring.boot>${skip.spring.boot}</skip.spring.boot>
                    </systemPropertyVariables>
                    <skip>${skip.spring.boot}</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <id>require-profile</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireProperty>
                                    <property>spring.profiles.active</property>
                                    <message>No profile! Use -Pusers, -Pservers, or -Ptests </message>
                                </requireProperty>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>generate-profile-properties</id>
                        <phase>process-resources</phase>
                        <configuration>
                            <target>
                                <mkdir dir="${project.build.outputDirectory}" />
                                <echo file="${project.build.outputDirectory}/profile.properties" append="false"><![CDATA[#AUTO-GENERATED
Profile=${spring.profiles.active}]]></echo>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.foomaa.jvchat.uilinks</groupId>
            <artifactId>UILinks</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.foomaa.jvchat.ctrl</groupId>
            <artifactId>Controls</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.foomaa.jvchat.tools</groupId>
            <artifactId>Tools</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.foomaa.jvchat.settings</groupId>
            <artifactId>Settings</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.foomaa.jvchat.logger</groupId>
            <artifactId>Logger</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
