name: Build project

on: push

jobs:
  dbbuild:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: sudo scripts/requirements/install_requirements.sh


    steps:
      - uses: actions/checkout@v3
      - name: Build DB
        run: |
            
            sudo scripts/db/make_default_db.sh

  build:
    needs: dbbuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          
          scripts/build/build.sh
    
