name: Linux

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3.1.0
      
      - name: Install requirements
        run: sudo /scripts/requirements/install_requirements.sh

      - name: Build DB
        run: sudo scripts/db/make_default_db.sh

      - name: Build chat
        run: scripts/build/build.sh
    
