name: Build project

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- name: set up JDK 17
        #uses: actions/setup-java@v1
        #with:
        #  java-version: 1.17
      - name: Build
        run: pwd; sudo bash scripts/db/make_default_db.sh; scripts/build/run.sh