name: Linux

on: push

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3.1.0
      
      - name: Install dependencies
        run: sudo scripts/dependencies/install_dependencies.sh -a -p servers

      - name: Build DB
        run: sudo scripts/db/make_default_db.sh

      - name: Dump and restore DB
        run: scripts/db/db_creator.py -r dump; scripts/db/db_creator.py -r restore

      - name: Build chat gradle tests
        run: scripts/build/build.sh -g -c -p tests

      - name: Build chat maven tests
        run: scripts/build/build_run.sh -m -c -p tests

      - name: Build chat gradle servers
        run: scripts/build/build.sh -g -c -p servers

      - name: Build chat maven servers
        run: scripts/build/build.sh -m -c -p servers

      - name: Build chat gradle users
        run: scripts/build/build.sh -g -c -p users

      - name: Build chat maven users
        run: scripts/build/build.sh -m -c -p users
    
