name: Linux

on: push

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3.1.0
      
      - name: Install dependencies
        run: sudo scripts/dependencies/install_dependencies.sh -a

      - name: Build DB
        run: sudo scripts/db/make_default_db.sh; scripts/db/db_creator.py -r dump; scripts/db/db_creator.py -r restore

      - name: Build chat gradle
        run: scripts/build/build.sh -g -c
        
      - name: Build chat maven
        run: scripts/build/build.sh -m -c
    
